
sudo: required
services:
- docker
os:
- linux
env:
  global:
  - DOCKER_IMAGE_NAME="containerd"
  - DOCKER_HUB_ORG="woka"
before_install:
- openssl aes-256-cbc -K $encrypted_b092a725a5c1_key -iv $encrypted_b092a725a5c1_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
- sudo chmod +x deploy.sh
- sudo chmod 600 deploy_rsa
after_script:
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:be-latest
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:be-latest
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR  'bash -s' < deploy.sh


