"""empty message

Revision ID: 99a78476b8f2
Revises: 
Create Date: 2020-01-04 15:55:40.910901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a78476b8f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konsumen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('client_password', sa.String(length=1000), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('telp', sa.String(length=13), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('kota', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipe', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nama_produk', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('berat', sa.Integer(), nullable=True),
    sa.Column('gambar', sa.String(length=200), nullable=True),
    sa.Column('preview_1', sa.String(length=200), nullable=True),
    sa.Column('preview_2', sa.String(length=200), nullable=True),
    sa.Column('preview_3', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('belanja',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('kurir', sa.String(length=10), nullable=True),
    sa.Column('ongkir', sa.Integer(), nullable=True),
    sa.Column('total_harga', sa.Integer(), nullable=True),
    sa.Column('payment', sa.String(length=20), nullable=True),
    sa.Column('bukti_pembayaran', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['produk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['konsumen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('belanja')
    op.drop_table('produk')
    op.drop_table('konsumen')
    # ### end Alembic commands ###
